### ISSUE TITLE
rest parameter is an ES6 feature

### ISSUE THREAD

**Issue by shivampandey0** [rahulcs754/neog_assignment#3]
In the below code the rest parameter is es6 feature so it can't be used for this problem because code has to be converted from es6 => es5

Use es5 features only

```
function packIt (...args){
    console.log(args);
}
let list = [1,2,3,4,5,6];

packIt(...list);
```

**Comment by rahulcs754** [comment]
function packIt() {
console.log( Object.values(arguments));
}


Is this correct. then please message me so i will close this issue

**Comment by shivampandey0** [comment]
I was discussing the `Object.values()` with Hamza.

`Object.keys()` was introduced in ES5 but couldn't find anything for `Object.values()`

So maybe if you can find a source to confirm this then maybe it'll be the right way to do.

If not then I'll ask this in today's doubt clearing session. :)

**Comment by rahulcs754** [comment]
sure we well discuss in doubt time
